  
version: '3.5'

services:
    app:
        build: .
        container_name: quotegeneric-front
        restart: always
        ports:
            - "8060:80"
        environment: 
            - NODE_ENV=production
            - PUBLIC_URL=https://sandbox.generic.com/quote-front/
            - PUBLIC_SERVICE_AUTH=https://sandbox.generic.com/auth/v1/
            - PUBLIC_SERVICE_CHARGEBACK=https://sandbox.generic.com/quote-front/v1/
        networks:
            - service-platform-nginx-network
networks:
    service-platform-nginx-network:
        external: true
